Add doc for porting plugins
Flow-Launcher/docs pull request #3
Opened 2021-02-17 21:40 UTC by jjw24

2021-02-18 01:25 UTC, Zeroto521 requested changes
using `#` title mark replace `:`

2021-02-18 01:25 UTC, Zeroto521 commented on port-plugins.md
> +Note:
`Note:` -> `## Note` level 2 title

2021-02-18 01:25 UTC, Zeroto521 commented on port-plugins.md
> +Steps:
`Steps:` -> `## Steps` level 2 title

2021-02-18 09:33 UTC, jjw24 commented
done, please take another look @Zeroto521

2021-02-18 13:51 UTC, Zeroto521 requested changes

2021-02-18 13:51 UTC, Zeroto521 commented on port-plugins.md
> +## Note:
![image](https://user-images.githubusercontent.com/25895405/108366233-19ff6a80-7233-11eb-90b8-b714e7e0dd61.png)

It is better don't add colon `:`, it doesn't look good.

2021-02-18 20:14 UTC, jjw24 commented
Done.

2021-02-19 02:03 UTC, Zeroto521 approved these changes

2021-02-19 02:44 UTC, merged